"""Adding metadata field to DBParams

Revision ID: 40fb2cd83300
Revises: 660fa00ad149
Create Date: 2026-01-09 09:20:45.420998

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40fb2cd83300"
down_revision: Union[str, Sequence[str], None] = "660fa00ad149"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    from basejump.core.database.db_connect import ConnectDB
    from basejump.internal.database.crud.crud_utils import (
        conn_params_noasync,
        gen_client_id_suffixes,
    )

    conn_db = ConnectDB(conn_params=conn_params_noasync)
    basejump_engine_noasync = conn_db.connect_db()
    suffixes = gen_client_id_suffixes(engine=basejump_engine_noasync, reverse=False, local_override=True)
    print("Running suffixes...", suffixes)
    print("Dropping views...")
    for suffix in suffixes:
        if not suffix or suffix == "0":
            continue
        for table in [
            # "connect.team_connection",
            # "connect.table_connection",
            # "connect.connection",
            "connect.database",
            # "connect.db_conn",
            # "connect.vector_db",
            # "connect.database_tables",
            # "connect.table_columns",
            # "connect.demo_vector",
            # "ai_model.user_chat_id",
            # "ai_model.prompt_history",
            # "ai_model.chat_history",
            # "ai_model.result_history",
            # "ai_model.visual_result_history",
            # "ai_model.saved_result_history",
            # "ai_model.token_count",
            # "ai_model.user_tokens",
            # "transaction.deposit_history",
            # "transaction.withdraw_history",
            # "transaction.basejump_credit_ledger",
        ]:
            table_name = f"{table.split('.')[0] + suffix}.{table.split('.')[1]}"
            # Drop the view
            print("Dropping view", table_name)
            op.execute(f"DROP VIEW IF EXISTS {table_name}")
    op.add_column("database", sa.Column("database_metadata", sa.LargeBinary(), nullable=True), schema="connect")
    print("Adding views...")
    for suffix in suffixes:
        if not suffix or suffix == "0":
            continue
        # Create views
        for table in [
            # "connect.team_connection",
            # "connect.table_connection",
            # "connect.connection",
            "connect.database",
            # "connect.db_conn",
            # "connect.vector_db",
            # "connect.database_tables",
            # "connect.table_columns",
            # "connect.demo_vector",
            # "ai_model.user_chat_id",
            # "ai_model.prompt_history",
            # "ai_model.chat_history",
            # "ai_model.result_history",
            # "ai_model.visual_result_history",
            # "ai_model.saved_result_history",
            # "ai_model.token_count",
            # "ai_model.user_tokens",
            # "transaction.deposit_history",
            # "transaction.withdraw_history",
            # "transaction.basejump_credit_ledger",
        ]:
            table_name_w_suffix = f"{table.split('.')[0] + suffix}.{table.split('.')[1]}"
            op.execute(
                f"""\
        CREATE VIEW {table_name_w_suffix} WITH(security_invoker=TRUE) AS \
        SELECT * FROM {table} \
        WHERE client_id = {suffix}"""
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError
