"""adding pk constraints on uuids

Revision ID: 51db0d589e76
Revises: 8b79f44be5c2
Create Date: 2026-02-23 15:57:27.286614

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51db0d589e76"
down_revision: Union[str, Sequence[str], None] = "8b79f44be5c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "team", ["team_id"], schema="account")
    op.create_unique_constraint(None, "team", ["team_uuid"], schema="account")
    op.create_unique_constraint(None, "user", ["user_uuid"], schema="account")
    op.create_unique_constraint(None, "chat_history", ["msg_uuid"], schema="ai_model")
    op.create_unique_constraint(None, "prompt_history", ["prompt_uuid"], schema="ai_model")
    op.create_unique_constraint(None, "result_history", ["result_uuid"], schema="ai_model")
    op.create_unique_constraint(None, "saved_result_history", ["saved_result_uuid"], schema="ai_model")
    op.create_unique_constraint(None, "token_count", ["token_uuid"], schema="ai_model")
    op.create_unique_constraint(None, "user_chat_id", ["chat_uuid"], schema="ai_model")
    op.create_unique_constraint(None, "visual_result_history", ["visual_result_uuid"], schema="ai_model")
    op.create_unique_constraint(None, "client_storage_conn", ["storage_uuid"], schema="connect")
    op.create_unique_constraint(None, "connection", ["conn_uuid"], schema="connect")
    op.create_unique_constraint(None, "database", ["db_uuid"], schema="connect")
    op.create_unique_constraint(None, "database_tables", ["tbl_uuid"], schema="connect")
    op.create_unique_constraint(None, "table_columns", ["col_uuid"], schema="connect")
    op.create_unique_constraint(None, "table_upload", ["upload_uuid"], schema="connect")
    op.create_unique_constraint(None, "vector_db", ["vector_uuid"], schema="connect")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vector_db", schema="connect", type_="unique")
    op.drop_constraint(None, "table_upload", schema="connect", type_="unique")
    op.drop_constraint(None, "table_columns", schema="connect", type_="unique")
    op.drop_constraint(None, "database_tables", schema="connect", type_="unique")
    op.drop_constraint(None, "database", schema="connect", type_="unique")
    op.drop_constraint(None, "connection", schema="connect", type_="unique")
    op.drop_constraint(None, "client_storage_conn", schema="connect", type_="unique")
    op.drop_constraint(None, "visual_result_history", schema="ai_model", type_="unique")
    op.drop_constraint(None, "user_chat_id", schema="ai_model", type_="unique")
    op.drop_constraint(None, "token_count", schema="ai_model", type_="unique")
    op.drop_column("token_count", "cost_per_1k_tokens_output", schema="ai_model")
    op.drop_column("token_count", "cost_per_1k_tokens_input", schema="ai_model")
    op.drop_constraint(None, "saved_result_history", schema="ai_model", type_="unique")
    op.drop_constraint(None, "result_history", schema="ai_model", type_="unique")
    op.drop_constraint(None, "prompt_history", schema="ai_model", type_="unique")
    op.drop_constraint(None, "chat_history", schema="ai_model", type_="unique")
    op.drop_constraint(None, "user", schema="account", type_="unique")
    op.drop_constraint(None, "team", schema="account", type_="unique")
    op.drop_constraint(None, "team", schema="account", type_="unique")
    # ### end Alembic commands ###
